project:
  type: website
  execute-dir: project

website:
  title: "WNBA Standings"
  navbar:
    background: primary
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Current Year"
        href: index.qmd
      - section: "Past Years"
        contents:
          - text: "2024"
            href: pages/2024.qmd
          - text: "2023"
            href: pages/2023.qmd
          - text: "2022"
            href: pages/2022.qmd
          - text: "2021"
            href: pages/2021.qmd
          - text: "2020"
            href: pages/2020.qmd
          - text: "2019"
            href: pages/2019.qmd
          - text: "2018"
            href: pages/2018.qmd
          - text: "2017"
            href: pages/2017.qmd
          - text: "2016"
            href: pages/2016.qmd
          - text: "2015"
            href: pages/2015.qmd
          - text: "2014"
            href: pages/2014.qmd
          - text: "2013"
            href: pages/2013.qmd
          - text: "2012"
            href: pages/2012.qmd
          - text: "2011"
            href: pages/2011.qmd
          - text: "2010"
            href: pages/2010.qmd
          - text: "2009"
            href: pages/2009.qmd
          - text: "2008"
            href: pages/2008.qmd
          - text: "2007"
            href: pages/2007.qmd
          - text: "2006"
            href: pages/2006.qmd
          - text: "2005"
            href: pages/2005.qmd
          - text: "2004"
            href: pages/2004.qmd
          - text: "2003"
            href: pages/2003.qmd
          - text: "2002"
            href: pages/2002.qmd
          - text: "2001"
            href: pages/2001.qmd
          - text: "2000"
            href: pages/2000.qmd
          - text: "1999"
            href: pages/1999.qmd
          - text: "1998"
            href: pages/1998.qmd
          - text: "1997"
            href: pages/1997.qmd
      - section: "Team Histories"
        contents:
          - text: "Atlanta Dream"
            href: pages/Atlanta Dream.qmd
          - text: "Chicago Sky"
            href: pages/Chicago Sky.qmd
          - text: "Connecticut Sun"
            href: pages/Connecticut Sun.qmd
          - text: "Dallas Wings"
            href: pages/Dallas Wings.qmd
          - text: "Golden State Valkyries"    
          - text: "Indiana Fever"
            href: pages/Indiana Fever.qmd
          - text: "Las Vegas Aces"
            href: pages/Las Vegas Aces.qmd
          - text: "Los Angeles Sparks"
            href: pages/Los Angeles Sparks.qmd
          - text: "Minnesota Lynx"
            href: pages/Minnesota Lynx.qmd
          - text: "New York Liberty"
            href: pages/New York Liberty.qmd
          - text: "Phoenix Mercury"
            href: pages/Phoenix Mercury.qmd
          - text: "Seattle Storm"
            href: pages/Seattle Storm.qmd
          - text: "Washington Mystics"
            href: pages/Washington Mystics.qmd
          - section: "Past Teams"
            contents:
              - text: "Charlotte Sting"
                href: pages/Charlotte Sting.qmd
              - text: "Cleveland Rockers"
                href: pages/Cleveland Rockers.qmd
              - text: "Detroit Shock"
                href: pages/Detroit Shock.qmd
              - text: "Houston Comets"
                href: pages/Houston Comets.qmd
              - text: "Miami Sol"
                href: pages/Miami Sol.qmd
              - text: "Orlando Miracle"
                href: pages/Orlando Miracle.qmd
              - text: "Portland Fire"
                href: pages/Portland Fire.qmd
              - text: "Sacramento Monarchs"
                href: pages/Sacramento Monarchs.qmd
              - text: "San Antonio Silver Stars"
                href: pages/San Antonio Silver Stars.qmd
              - text: "Tulsa Shock"
                href: pages/Tulsa Shock.qmd
              - text: "Utah Starzz"
                href: pages/Utah Starzz.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: [flatly, light.scss]
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true



