---
title: "Dallas Wings"
format: 
  html:
    fig-width: 10
    fig-height: 6
    toc: false
lightbox: true
---

### Franchise History

```{r}
#| echo: false
#| message: false
#| results: asis
source('code/setupStandings.R')
source('code/setupElo.R')

team <- "Dallas Wings"
abbr1 <- teamcolors$team[teamcolors$name == team]
abbr2 <- allgames$home_team_abbr[which(allgames$`Home/Neutral` == team)[1]]
if(is.na(abbr2)){
    abbr2 <- abbr1
}
allnames <- unique(allgames$`Home/Neutral`[which(allgames$home_team_abbr == abbr2)])
allabbrs <- teamcolors$team[match(allnames, teamcolors$name)]

ranges <- lapply(allnames, function(team){
    range(allgames$season[allgames$`Home/Neutral` == team])
})


for(i in 1:length(allnames)){
    if(ranges[[i]][2] == 2024){
            text <- paste0(allnames[i], " (", ranges[[i]][1], " - Present)")
    }else{
            text <- paste0(allnames[i], " (", ranges[[i]][1], " - ", ranges[[i]][2], ")")
    }
    cat(paste0(" - [",text,"](",allnames[i],".qmd)"))
    cat('\n')
}
cat('\n')
```





```{r}
#| echo: false
#| message: false
#| classes: light-mode
layout(matrix(1:28,nrow=4,byrow = TRUE))
par(mar=c(.1,.2,1,.2))
for(year in 1997:2024){
    makeWNBAeloHiliteGraph(year, team, allnames, allgames)
}
layout(matrix(1))
par(mar=c(5,4,4,2)+.1)
```

```{r}
#| echo: false
#| message: false
#| classes: dark-mode
layout(matrix(1:28,nrow=4,byrow = TRUE))
par(mar=c(.1,.2,1,.2))
for(year in 1997:2024){
    makeWNBAeloHiliteGraph(year, team, allnames, allgames, mode = 'dark')
}
layout(matrix(1))
par(mar=c(5,4,4,2)+.1)
```

