---
title: "Houston Comets"
format: 
  html:
    fig-width: 10
    fig-height: 6
    toc: false
lightbox: true
---

### Franchise History

```{r}
#| echo: false
#| message: false
#| results: asis
source('code/setup.R')
source('code/utils.R')
source('code/plotting.R')

team <- "Houston Comets"
franchise <- teamdata$franchise[teamdata$team == team]

allnames <- unique(allgames$`Home/Neutral`[which(allgames$home_franchise == franchise)])
allnames <- c(allnames, unique(allgames$`Visitor/Neutral`[which(allgames$away_franchise == franchise)]))
allnames <- unique(allnames)
allabbrs <- teamdata$abbr[match(allnames, teamdata$team)]

ranges <- lapply(allnames, function(team){
    range(allgames$season[allgames$`Home/Neutral` == team | allgames$`Visitor/Neutral` == team])
})

for(i in 1:length(allnames)){
    if(ranges[[i]][2] == 2025){
            text <- paste0(allnames[i], " (", ranges[[i]][1], " - Present)")
    }else{
            text <- paste0(allnames[i], " (", ranges[[i]][1], " - ", ranges[[i]][2], ")")
    }
    cat(paste0(" - [",text,"](",allnames[i],".qmd)"))
    cat('\n')
}
cat('\n')
```





```{r}
#| echo: false
#| message: false
#| classes: light-mode
layout(matrix(1:30,nrow=5,byrow = TRUE))
par(mar=c(.1,.2,1,.2))
for(year in 1997:2025){
    makeWNBAeloHiliteGraph(year, team, allnames, allgames)
}
layout(matrix(1))
par(mar=c(5,4,4,2)+.1)
```

```{r}
#| echo: false
#| message: false
#| classes: dark-mode
layout(matrix(1:30,nrow=5,byrow = TRUE))
par(mar=c(.1,.2,1,.2))
for(year in 1997:2025){
    makeWNBAeloHiliteGraph(year, team, allnames, allgames, mode = 'dark')
}
layout(matrix(1))
par(mar=c(5,4,4,2)+.1)
```


```{r}
#| echo: false
#| message: false
#| results: asis

years <- sort(unique(allgames$season))
champs <- sapply(years, function(yr){
	lastgame <- allgames[which(allgames$season == yr), ]
    lastgame <- lastgame[which.max(lastgame$Date), ]
    champ <- ifelse(lastgame$PTShome > lastgame$PTSvis, lastgame$`Home/Neutral`, lastgame$`Visitor/Neutral`)
    return(champ)
})
if(team %in% champs){
	cat("### Championships")
	cat('\n')
	idx <- which(champs == team)
	for(ii in idx){
		cat(paste0(" - [",years[ii],"](",years[ii],".qmd)"))
    	cat('\n')
	}
}

```

